parameters:

    erpdataio.logger.class: "ERPDataIO\\ERPDataIOCoreBundle\\Services\\ERPDataIOLogger"
    erpdataio.manager.importer.class: "ERPDataIO\\ERPDataIOCoreBundle\\Services\\DataImportManager"