services:

    erpdataio.logger:
        class: %erpdataio.logger.class%
        arguments:
            logger: @logger
            active: %erpdataio.logger.active%
            level: %erpdataio.logger.level%
        tags:
            - { name: monolog.logger, channel: 'erpdataio' }

    erpdataio.importer:
        class: %erpdataio.manager.importer.class%
        arguments:
            manager: @doctrine.orm.entity_manager
            container: @service_container