#!/usr/bin/env php
<?php

umask(0000);

set_time_limit(0);

require_once(__DIR__.'/../../../../../../vendor/autoload.php');
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
use ERPDataIO\ERPDataIOCoreBundle\Command\ImportDataCommand;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel  = new AppKernel($env, $debug);
$console = new Application($kernel);
// $console->addCommands(array(
//     new ImportDataCommand(),
//     // more commands...
// ));

$console->run($input);
